-- disable netrw at the very start of your init.lua (strongly advised)
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1

require("adrmo.packer")
require("adrmo.core.options")
require("adrmo.core.keymaps")
require("adrmo.plugins.comment")
require("adrmo.plugins.nvim-tree")
require("adrmo.plugins.lualine")
require("adrmo.plugins.telescope")
require("adrmo.plugins.nvim-cmp")
require("adrmo.plugins.lsp.lsp")
require("adrmo.plugins.luasnip")
require("adrmo.plugins.autopairs")
require("adrmo.plugins.treesitter")
require("adrmo.plugins.gitsigns")
require("adrmo.plugins.dap")
require("adrmo.plugins.dap-ui")
require("adrmo.plugins.neoscroll")
require("adrmo.plugins.bufferline")
require("adrmo.plugins.alpha")
require("adrmo.plugins.which-key")
require("adrmo.core.colorscheme")
require("adrmo.plugins.project")
require("adrmo.plugins.trouble")
require("adrmo.plugins.toggleterm")
